obj-$(CONFIG_SND_SOC_OPV5XC) += snd-soc-opv5xc.o
snd-soc-opv5xc-objs := opv5xc-platform.o

obj-$(CONFIG_SND_SOC_OPV5XC_I2S) += snd-soc-opv5xc-i2s.o
snd-soc-opv5xc-i2s-objs := opv5xc-i2s.o

obj-$(CONFIG_SND_SOC_OPV5XC_TLV320AIC23) += snd-soc-opv5xc-tlv320aic23.o
snd-soc-opv5xc-tlv320aic23-objs := opv5xc-tlv320aic23.o
