#
# Makefile for the phy drivers.
#

obj-$(CONFIG_GENERIC_PHY)	+= phy-core.o
obj-$(CONFIG_BROADCOM_CMIC_MDIO)	+= broadcom_cmic_mdio.o
obj-$(CONFIG_PHY_BCM_NS2_SATA)		+= phy-bcm-ns2-sata.o
obj-$(CONFIG_PHY_MVEBU_COMPHY)		+= phy-mvebu-comphy.o
