#/**************************************************************************
# * Copyright 2010-2014, Freescale Semiconductor, Inc. All rights reserved.
# ***************************************************************************/
#/*
# * File:       Makefile
# *
# */
obj-y += asfffp/driver/
obj-y += asfctrl/linux/ffp/
obj-y += asfipsec/driver/
obj-y += asfctrl/linux/ipsec/
#obj-y += asfqos/driver/
#obj-y += asfctrl/linux/qos/
