#/**************************************************************************
#  * Copyright 2010-2013, Freescale Semiconductor, Inc. All rights reserved.
# ***************************************************************************/
#/*
# * File:	Makefile
# *
# * Authors:	Hemant Agrawal <hemant@freescale.com>
# *
# */

include $(srctree)/drivers/net/asf/asfmodule/asfconfig.mk
obj-y := \
             asfctrl_linux_ipsec.o asfctrl_linux_ipsec_hooks.o
