#
# Makefile for the Linux Kernel SOC specific device drivers.
#

obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-$(CONFIG_QUICC_ENGINE_V03)	+= qe_v03/
obj-$(CONFIG_FSL_SOC_DRIVERS)	+= fsl/
obj-$(CONFIG_ARCH_ZYNQMP)	+= xilinx/zynqmp/
