#
# Makefile to build the network driver for BRCM - sf2
#

obj-$(CONFIG_NET_BCM_AMAC) += bcmamac.o

bcmamac-y :=  bcm-amac-enet.o bcm-amac-gphy.o bcm-amac-core.o bcm-amac-dbg.o bcm-robo.o bcm-amac-ethtool.o
