#/**************************************************************************
# * Copyright 2010-2011, Freescale Semiconductor, Inc. All rights reserved.
# ***************************************************************************/
#/*
# * File:	Makefile
# *
# * Authors:	Hemant Agrawal <hemant@freescale.com>
# *
# *
# */
.PHONY: all
all: build

build:
	make -w -C linux -f Makefile

#--------------------------------------------------------------
.PHONY: clean
clean:
	make -w -C linux -f Makefile clean
