#/**************************************************************************
#  * Copyright 2012, Freescale Semiconductor, Inc. All rights reserved.
# ***************************************************************************/
#/*
# * File:	Makefile
# *
# * Authors:	Sachin Saxena <sachin.saxena@freescale.com>
# *
# */
include $(srctree)/drivers/net/asf/asfmodule/asfconfig.mk
obj-y := asfctrl_linux_qos.o